# Generated by Django 2.2.4 on 2019-08-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('用户名', models.CharField(max_length=16)),
                ('密码', models.CharField(max_length=32)),
                ('邮箱', models.EmailField(max_length=254, null=True)),
                ('头像', models.ImageField(default='/statics/web/avatars/default-avatar.jpg', upload_to='statics/web/avatars')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suffix', models.CharField(max_length=16)),
                ('theme', models.CharField(max_length=16)),
                ('title', models.CharField(max_length=32)),
                ('summary', models.CharField(max_length=128)),
                ('uid', models.ForeignKey(on_delete=True, to='repository.User', unique=True)),
            ],
        ),
    ]
