# Generated by Django 2.2.4 on 2019-08-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_auto_20190829_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='web/avatars/default-avatar.jpg', upload_to='web/avatars', verbose_name='头像'),
        ),
    ]
