# Generated by Django 2.2.4 on 2019-09-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0005_auto_20190905_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='fly', max_length=16, verbose_name='昵称'),
            preserve_default=False,
        ),
    ]
