# Generated by Django 2.2.4 on 2019-09-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0006_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='theme',
            field=models.CharField(default='default', max_length=16, verbose_name='主题'),
        ),
    ]
