# Generated by Django 2.2.4 on 2019-09-10 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0007_auto_20190910_2053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='uid',
        ),
        migrations.AddField(
            model_name='blog',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='repository.User', verbose_name='用户'),
            preserve_default=False,
        ),
    ]
