# Generated by Django 2.2.1 on 2019-09-24 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0008_auto_20190910_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='repository.User', verbose_name='作者'),
            preserve_default=False,
        ),
    ]
