# Generated by Django 2.2.1 on 2019-09-24 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0009_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='down_count',
            field=models.PositiveIntegerField(default=0, verbose_name='踩数量'),
        ),
        migrations.AlterField(
            model_name='article',
            name='up_count',
            field=models.PositiveIntegerField(default=0, verbose_name='点赞数量'),
        ),
    ]
