# Generated by Django 2.2.4 on 2019-09-29 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0011_remove_tag_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='blog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='repository.Blog', verbose_name='博客'),
            preserve_default=False,
        ),
    ]
